.read ../create_tables/create_drive_stats_2013.sql
.read ../create_tables/create_drive_stats_2014.sql
.read ../create_tables/create_drive_stats_2015.sql
.read ../create_tables/create_drive_stats_2016.sql
.read ../create_tables/create_drive_stats_2017.sql
.read ../create_tables/create_drive_stats_2018_q1.sql
.read ../create_tables/create_drive_stats_2018_q2.sql
.read ../create_tables/create_drive_stats_2018_q3.sql
.read ../create_tables/create_drive_stats_2018_q4.sql
.read ../create_tables/create_drive_stats_2019.sql
.read ../create_tables/create_drive_stats_2020.sql
.read ../create_tables/create_drive_stats_2021_q1.sql
.read ../create_tables/create_drive_stats_2021_q2.sql
.read ../create_tables/create_drive_stats_2021_q3.sql
.read ../create_tables/create_drive_stats_2021_q4.sql